name: Practica CI

# Executar tests en tots els PR
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Fer test
      run: |
        echo aaa
